# Generated by Django 5.1.2 on 2024-11-26 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='prueba',
        ),
    ]
