# Generated by Django 5.1.3 on 2024-12-04 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='created_at',
        ),
    ]
