# Generated by Django 5.1.3 on 2024-12-04 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_remove_task_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='updated_at',
        ),
    ]
