# Generated by Django 5.1.3 on 2024-12-05 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_remove_task_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='user',
        ),
    ]
