# Generated by Django 5.1.3 on 2024-12-06 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_remove_service_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='driver',
        ),
    ]
