# Generated by Django 5.1.3 on 2024-12-13 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_jobassignment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobassignment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='pending', max_length=50),
        ),
    ]
