# Generated by Django 5.1.3 on 2024-12-15 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_order_contact_number_order_details'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DriverAssignment',
        ),
    ]
