# Generated by Django 5.1.3 on 2024-12-16 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_delete_driverassignment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobassignment',
            old_name='employee',
            new_name='assigned_to',
        ),
    ]
